[package]
name = "block"
version = "0.1.0"
authors = ["anand2312 <anandkrishna2312@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json = "*"
structopt = "0.3.13"
regex = "1"
